# Generated by Django 5.0.2 on 2024-11-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryentry',
            name='image',
        ),
        migrations.RemoveField(
            model_name='habitentry',
            name='image',
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='image',
        ),
    ]
