# Generated by Django 5.0.2 on 2024-11-02 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_habitentry_user_habit_alter_habitentry_habit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitentry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='habitentry',
            name='duration',
        ),
        migrations.AddField(
            model_name='habitentry',
            name='duration_minutes',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitentry',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitentry',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
