# Generated by Django 5.0.2 on 2024-11-04 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_habitentry_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='places', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surrounding',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='surroundings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='theme',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='themes', to=settings.AUTH_USER_MODEL),
        ),
    ]
