# Generated by Django 5.0.2 on 2024-11-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_place_user_surrounding_user_theme_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='sleep_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='temperature',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
