# Generated by Django 5.0.2 on 2024-11-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_moodentry_sleep_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='emotions',
            field=models.ManyToManyField(related_name='mood_entries', to='app.emotion'),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='exercise_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='sleep_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='steps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='temperature',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='weather_condition',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
