# Generated by Django 5.0.2 on 2024-12-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_moodentry_emotions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='user',
        ),
        migrations.RemoveField(
            model_name='surrounding',
            name='user',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='user',
        ),
    ]
